### PR TITLE
resolves #132 add support for AF_UNIX bind on macOS

### LINKED ISSUE #132: Unable to listen to unix domain socket inside bindfs mount on macOS
Way to reproduce:

(as root)

1. macOS Ventura + macFUSE 4.5.0 + bindfs 1.17.3
```
$ mkdir a
$ mkdir b
$ bindfs a b
$ nc -U b/sock -l
nc: Invalid argument
$ nc -U a/sock -l
<works>
```
2. macOS Ventura + fuse-t 1.0.23 + bindfs 1.17.3
```
$ mkdir a
$ mkdir b
$ bindfs a b
$ nc -U b/sock -l
nc: Input/output error
$ nc -U a/sock -l
<works>
```
If this issue is not caused by bindfs, my apologies, will report to macFUSE/fuse-t.

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

File: src/bindfs.c [hunk 1]
```diff
@@ -904,10 +906,37 @@ static int bindfs_mknod(const char *path, mode_t mode, dev_t rdev)
...
+        if (fd >= 0) {
+            /*
+             * We must bind the socket to the underlying file
+             * system to create the socket file, even though
+             * we'll never listen on this socket.
+             */
+            su.sun_family = AF_UNIX;
+            strncpy(su.sun_path, real_path, sizeof(su.sun_path));
+            res = bind(fd, (struct sockaddr*)&su, sizeof(su));
+            if (res == 0)
```
Comment (mpartel) [inline src/bindfs.c:930]: Don't we need to close regardless of `bind`'s success?

**Review by mpartel — COMMENTED** [review]
Thanks, this looks good aside from 1 comment. I'll try this out and possibly write a unit test either later today or tomorrow.

File: src/bindfs.c (hunk 1 above)
Comment (slonopotamus) [reply src/bindfs.c:930]: I don't think so. `nc` wants to read from it. I'll test what happens in case we close it later today. As I understand, you're worried that file descriptor will leak in case listening process dies? Need to think about it... I'll also take a look at how you handle the same issue with `fopen`.

Comment (slonopotamus) [reply src/bindfs.c:930]: Oh, we don't return `fd` anywhere. Maybe you're right. Will test and update accordingly.

Comment (slonopotamus) [reply src/bindfs.c:930]: I drank some more coffee, you're right, we're just leaking socket fd into the void.

Comment (slonopotamus) [reply src/bindfs.c]: I've tested, everything works properly with unconditional socket closing. Updated PR.

**Comment by mpartel** [comment]
Merged, thanks!
I've no idea why the test suite (`make check`) fails on my machine with "short read on fuse device", but otherwise this seems to work, and I added build support for fuse-t too.

**Comment by slonopotamus** [comment]
I'm also getting "short read on fuse device" test failure with fuse-t. macFUSE passes properly. Possibly need to create one more issue against fuse-t given that bindfs side is now fully-functional.

**Comment by mpartel** [comment]
The test failure is a strange one given that the exact same bindfs command that the test invokes works when invoked directly. I'd need to figure out how the test environment is different, but probably don't have time for that today. Created issue #135

**Comment by mpartel** [comment]
Released as 1.17.4
